### ISSUE TITLE
segmentation violation when using root_numpy with matplotlib

### ISSUE THREAD

**Issue by samtygier** [rootpy/root_numpy#180] opened 2015-03-17 16:52 UTC
I am getting a crash that looks similar to that in #66

I can trigger it with the same 1 line example

```
python -c 'import ROOT as R; import root_numpy; import matplotlib.pyplot as P; f = R.TMemFile("test.root", "recreate"); P.figure(); P.show()'
```

I am using
ROOT 5.34.26 built from source
root_numpy built from git cb53ea3b0dacc33f44326f14d78b5f84e51bbfec (10 Mar 2015)
matplotlib 1.4.2 from ubuntu python-matplot 1.4.2-3.1 package
on ubuntu 15.04

backtrace

```
*** Break *** segmentation violation
 Generating stack trace...
 0x00007f8824446b36 in XGetDefault + 0xc6 from /usr/lib/x86_64-linux-gnu/libX11.so.6
 0x00007f88253f7e1f in <unknown> from /usr/lib/x86_64-linux-gnu/libcairo.so.2
 0x00007f88253fa390 in <unknown> from /usr/lib/x86_64-linux-gnu/libcairo.so.2
 0x00007f88253caf77 in cairo_surface_get_font_options + 0x87 from /usr/lib/x86_64-linux-gnu/libcairo.so.2
 0x00007f882538900c in <unknown> from /usr/lib/x86_64-linux-gnu/libcairo.so.2
 0x00007f882538d072 in <unknown> from /usr/lib/x86_64-linux-gnu/libcairo.so.2
 0x00007f882537f1b2 in cairo_glyph_path + 0x22 from /usr/lib/x86_64-linux-gnu/libcairo.so.2
 0x00007f8824766091 in <unknown> from /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
 0x00007f882476648f in <unknown> from /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
 0x00007f8824b97c59 in pango_renderer_draw_glyphs + 0x39 from /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
 0x00007f8824b98648 in pango_renderer_draw_layout_line + 0x4a8 from /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
 0x00007f8824b989d5 in pango_renderer_draw_layout + 0x115 from /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
 0x00007f882476663a in <unknown> from /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
 0x00007f881df73afd in <unknown> from /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libmurrine.so
 0x00007f8825a50a49 in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f8825a5bd1f in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f882643e22f in g_closure_invoke + 0x9f from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f882644ff32 in <unknown> from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f88264581a5 in g_signal_emit_valist + 0xae5 from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f88264588ff in g_signal_emit + 0x8f from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f8825b7361c in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f88259e1478 in gtk_container_propagate_expose + 0x198 from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f88259dff3c in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f8825a5bd1f in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f882643e22f in g_closure_invoke + 0x9f from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f882644ff32 in <unknown> from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f88264581a5 in g_signal_emit_valist + 0xae5 from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f88264588ff in g_signal_emit + 0x8f from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f8825b7361c in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f88259e1478 in gtk_container_propagate_expose + 0x198 from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f8825b24d7e in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f8825a5bd1f in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f882643e22f in g_closure_invoke + 0x9f from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f882644ff32 in <unknown> from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f88264581a5 in g_signal_emit_valist + 0xae5 from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f88264588ff in g_signal_emit + 0x8f from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f8825b7361c in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f88259e1478 in gtk_container_propagate_expose + 0x198 from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f88259ac86a in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f88259dff3c in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f8825a5bd1f in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f882643e22f in g_closure_invoke + 0x9f from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f882644ff32 in <unknown> from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f88264581a5 in g_signal_emit_valist + 0xae5 from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f88264588ff in g_signal_emit + 0x8f from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f8825b7361c in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f88259e1478 in gtk_container_propagate_expose + 0x198 from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f88259dff3c in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f8825a5bd1f in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f882643e2d5 in g_closure_invoke + 0x145 from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f882644ff32 in <unknown> from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f88264581a5 in g_signal_emit_valist + 0xae5 from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f88264588ff in g_signal_emit + 0x8f from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 0x00007f8825b7361c in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f8825a5aaa2 in gtk_main_do_event + 0x552 from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f88256b4bdf in <unknown> from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
 0x00007f88256b16b8 in <unknown> from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
 0x00007f88256b1fe8 in gdk_window_process_all_updates + 0x118 from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
 0x00007f88259dfbd1 in <unknown> from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f8825690dd7 in <unknown> from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
 0x00007f8826fa2b4d in g_main_context_dispatch + 0x15d from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 0x00007f8826fa2f20 in <unknown> from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 0x00007f8826fa3242 in g_main_loop_run + 0xc2 from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 0x00007f8825a59857 in gtk_main + 0xb7 from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 0x00007f88261224e7 in <unknown> from /usr/lib/python2.7/dist-packages/gtk-2.0/gtk/_gtk.so
 0x00000000004cda58 in PyEval_EvalFrameEx + 0x918 from python
 0x00000000004cbe31 in PyEval_EvalCodeEx + 0x411 from python
 0x00000000004ceeeb in PyEval_EvalFrameEx + 0x1dab from python
 0x00000000004e7ef8 in <unknown> from python
 0x000000000050bb38 in <unknown> from python
 0x00000000005735fd in <unknown> from python
 0x00000000004cf879 in PyEval_EvalFrameEx + 0x2739 from python
 0x00000000004cbe31 in PyEval_EvalCodeEx + 0x411 from python
 0x00000000004ceeeb in PyEval_EvalFrameEx + 0x1dab from python
 0x00000000004cbe31 in PyEval_EvalCodeEx + 0x411 from python
 0x000000000054266a in PyRun_StringFlags + 0x8a from python
 0x000000000054327a in PyRun_SimpleStringFlags + 0x3a from python
 0x000000000049ac82 in Py_Main + 0x3a2 from python
 0x00007f8834f1bec5 in __libc_start_main + 0xf5 from /lib/x86_64-linux-gnu/libc.so.6
 0x000000000049a7f0 in <unknown> from python
```

**Comment by kratsg** [comment] 2015-03-17 16:58
This does not segfault for me. Using 5.34/23:

```python
>>> root_numpy.__version__
'3.3.1'
>>> numpy.__version__
'1.9.1'
>>> matplotlib.__version__
'1.4.2'
```

**Comment by samtygier** [comment] 2015-03-17 18:00
I tried checking out and installing root_numpy 3.3.1, but I still see the same issue. Also spotted that I typoed my ROOT version. I actually have root-5.34.26.

Also a full backtrace, if that's useful http://paste.ubuntu.com/10616576/

The kTRUE trick from #66 helps for the 1 liner, but not for my actual code.

**Comment by kratsg** [comment] 2015-03-17 18:03
Here's what I don't understand @samtygier -- you're not using anything from `root_numpy` to trigger this. Your one-liner shows this. Your backtrace shows this.

**Comment by samtygier** [comment] 2015-03-17 18:13
```
python -c 'import ROOT as R;  import matplotlib.pyplot as P; f = R.TMemFile("test.root", "recreate"); P.figure(); P.show()'
```

does not crash. So it looks like it need root_numpy to be loaded in order for it to trigger. Anything else I could try?

**Comment by ndawe** [comment] 2015-03-17 23:26
hmm.. this looks like #66. Definitely a threading issue and could be difficult to debug or reproduce. This doesn't crash for me but my conditions are not identical. I'll see what I can do...

**Comment by ndawe** [comment] 2015-03-17 23:29
I don't think this is specifically a root_numpy problem, but rather ROOT and matplotlib generally not playing nice together.

**Comment by kratsg** [comment] 2015-03-18 00:18
I think one thing we can try is the following, if it is indeed the imaging backends not playing nicely (happens a TON)

```
ROOT.gROOT.SetBatch(True)
```

to force ROOT to run in batch mode, which should turn off any calls to X11 or something similar. Then we can see if it goes away. If it does, it's probably `matplotlib` and `ROOT` backend libraries intersecting. And then you can try something like

```
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as pl
```

as referred to here: http://matplotlib.org/api/matplotlib_configuration_api.html#matplotlib.use

(Agg is more or less to turn off any interactivity and works on most *nix flavors).

**Comment by piti118** [comment] 2015-03-18 00:31
Long shot but try matplotlib from pip instead.

**Comment by samtygier** [comment] 2015-03-18 18:29
```
ROOT.gROOT.SetBatch(True)
```

Stops the issue. I am using matplotlib for plotting so I dont need ROOTs gui, I just need to extract some data from the root file.

**Comment by piti118** [comment] 2015-03-18 18:34
So the question is: should ROOT.gROOT.SetBatch(True) be the default.

I think we have seen this problem before couple times.

**Comment by kratsg** [comment] 2015-03-18 19:00
@piti118 -- this is ROOT's issue. ROOT loads up an X11 gui to make things work over threads and the problem ends up being when both ROOT and matplotlib are trying to use the same "window". Just turning off ROOT's batch mode when you use matplotlib is pretty much the only fix since `root_numpy` can be included with `ROOT` and not `matplotlib` and things should work fine. We can't obviously just force batch mode to be enabled...

**Comment by ndawe** [comment] 2015-03-18 22:57
Yeah, we should not force batch mode. This would be evil. I don't think we can do much about this here at the moment. I can't reproduce the crash on my end. Let's just keep this issue in mind, but close it for now.

**Closed** 2015-03-18 22:58 UTC
