### ISSUE TITLE
problems with root-config on windows

### ISSUE THREAD

**Issue by gevorgdavoyan** [rootpy/root_numpy#179] opened 2015-03-11 18:59 UTC
Is it possible to install root_numpy on windows? 
I am trying to install root_numpy on my windows machine, but always get an error:
  Running setup.py (path:c:\users\dell\appdata\local\temp\pip_build_DELL\root-nu
mpy\setup.py) egg_info for package root-numpy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "c:\users\dell\appdata\local\temp\pip_build_DELL\root-numpy\setup.py"
, line 61, in <module>
        rootsys, root_config))
    RuntimeError: ROOTSYS is C:\root but running C:\root\bin\root-config failed
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "c:\users\dell\appdata\local\temp\pip_build_DELL\root-numpy\setup.py", li
ne 61, in <module>

although everything is already installed, ROOTSYS is correctly set to C:\root and root-config is in C:\root\bin.

**Comment by kratsg** [comment] 2015-03-11 19:15
According to your traceback (which I have a hard time reading), you're seeing an error with the following line:

```
        root_config = os.path.join(rootsys, 'bin', 'root-config')
```

https://github.com/rootpy/root_numpy/blob/master/setup.py#L61

```python
    try:
        root_config = os.path.join(rootsys, 'bin', 'root-config')
        root_cflags, root_ldflags = root_flags(root_config)
    except OSError:
        raise RuntimeError(
            "ROOTSYS is {0} but running {1} failed".format(
                rootsys, root_config))
```

The problem is listed in your traceback however: 
```
RuntimeError: ROOTSYS is C:\root but running C:\root\bin\root-config failed
```

which points to a misconfiguration in your `root-config`. I'm not sure how you installed it, what version you installed, but it should usually be inside of a cygwin installation on Windows (which is probably the worst operating system to get ROOT installed on to be honest).

**Comment by ndawe** [comment] 2015-03-11 23:00
We don't officially support Windows (to be honest I've never even tried to build ROOT and root_numpy on Windows). But it would be interesting to know if/how it can be supported. What happens when you run C:\root\bin\root-config from a command prompt?

**Comment by gevorgdavoyan** [comment] 2015-03-12 10:22
Nothing happens, may be Windows does't know what it is, but running for example 'root-config --cflags' from Cygwin works and causes an error:

root-config: line 420: test: command: integer expression expected
-include:_G__cpp_setupG__Net -include:_G__cpp_setupG__IO -include:_G__cpp_setupG__Hist -include:_G__cpp_setupG__Graf -include:_G__cpp_setupG__G3D -include:_G__cpp_setupG__GPad -include:_G__cpp_setupG__Tree -include:_G__cpp_setupG__Thread -include:_G__cpp_setupG__Rint -include:_G__cpp_setupG__PostScript -include:_G__cpp_setupG__Matrix -include:_G__cpp_setupG__Physics 'C:\root\lib\libCore.lib' 'C:\root\lib\libCint.lib' 'C:\root\lib\libRIO.lib' 'C:\root\lib\libNet.lib' 'C:\root\lib\libHist.lib' 'C:\root\lib\libGraf.lib' 'C:\root\lib\libGraf3d.lib' 'C:\root\lib\libGpad.lib' 'C:\root\lib\libTree.lib' 'C:\root\lib\libRint.lib' 'C:\root\lib\libPostscript.lib' 'C:\root\lib\libMatrix.lib' 'C:\root\lib\libPhysics.lib' 'C:\root\lib\libMathCore.lib' 'C:\root\lib\libThread.lib'

**Comment by kratsg** [comment] 2015-03-12 13:09
This isn't a problem with `root-numpy` if `root-config` doesn't work. You'll need to go to the ROOT forums and get some help there, most likely.

**Comment by ndawe** [comment] 2015-03-13 01:19
Closing for now, but we can reopen later if you get root-config working and root_numpy still fails to build.

**Closed by ndawe** 2015-03-13 01:19 UTC

**Comment by tata-antares** [comment] 2016-03-18 17:59
Hey!

@ndawe I posted this problem on the ROOT forum https://root.cern.ch/phpBB3/viewtopic.php?t=19994. They need  exact info which is used from root-config for root_numpy installation.

About testing on Windows you can use appveyor, here is an [appveyor file](https://github.com/yandex/rep/blob/619a3d82c45efeb748fac2f1883668b56079dbed/appveyor.yml), which I used to test rep on Windows including ROOT and rooot_numpy installation.

**Comment by ndawe** [comment] 2016-03-30 02:39
Windows isn't a supported OS at this time, unfortunately. Does ROOT6 even compile on Windows? I'm not even sure if ROOT still supports Windows.

**Comment by ndawe** [comment] 2016-03-30 02:41
https://root.cern.ch/build-prerequisites#windows

**Comment by ndawe** [comment] 2016-03-30 02:44
root-config is a bash script, so won't run on Windows. I think it's up to the ROOT devs to provide a Windows equivalent.
