### ISSUE TITLE
support for string types in array2tree

### ISSUE THREAD

**Issue by MaxNoe** [rootpy/root_numpy#205] opened 2015-06-11 20:09 UTC
Support for numpy string dtypes would be great.

**Comment by ndawe** [comment] 2015-06-11 23:18
Do you mean for the conversion of numpy arrays into TTrees?

**Comment by MaxNoe** [comment] 2015-06-12 10:01
Yes, most important for me would be the fixed length string types like `numpy.dtype('S10')`,
to save something like datestamps into the rootfiles.

This would ownly need conversion from numpy arrays with dtype(Sx) to char* arrays with char[x+1] entries.

**Comment by ndawe** [comment] 2015-06-12 13:28
Yes, this is certainly possible. I'll start implementing it. Another solution in the meantime would be to convert the date string into an integer timestamp like http://stackoverflow.com/a/9637908 and array2root or array2tree will convert that.

**Comment by MaxNoe** [comment] 2015-06-12 13:31
Thats what I'm doing right now, but there are some things better described as String (source names etc).

Great!

**Comment by ndawe** [comment] 2015-06-13 14:00
Preliminary code is implemented in c26bd7ccf. Can you give this a try? I'm planning on extending that to handle fixed-length arrays of all basic types.

**Comment by ndawe** [comment] 2015-06-13 14:02
Install from my master branch:
```
pip install --upgrade --user https://github.com/ndawe/root_numpy/zipball/master
```

**Comment by MaxNoe** [comment] 2015-06-14 11:49
Writing works, thanks for that.

But reading is not working properly, the strings are converted into a list of integers,
the ascii codes of the letters to be precise.

```{python}
import numpy as np
import root_numpy as rnp


data = np.array(['2015-01-01', '2015-01-02'], dtype=[('date', 'S10')])

rnp.array2root(data, 'test.root', treename='data', mode='recreate')

data = rnp.root2array('test.root', treename='data')

print(data)
```

The Result is:
```
[[50 48 49 53 45 48 49 45 48 49]
 [50 48 49 53 45 48 49 45 48 50]]
```

**Comment by ndawe** [comment] 2015-06-14 13:22
Yes, I forgot to mention this. root_numpy treats arrays of each type "equally" so it really is an array of char bytes (np.int8). If you want to view the char array as strings then use ``data.view('S10')``. That interprets the underlying bytes as strings without making a copy. root_numpy needs to pick one default view since the original array could be of the equivalent type np.int8, but there is no way of determining the original view used on the input data before the array2tree+tree2array cycle. So if you originally viewed the data as S, then this extra ``view()`` step is required.

**Comment by ndawe** [comment] 2015-06-14 13:24
Extending your example:
```python
>>> import numpy as np
>>> import root_numpy as rnp
>>> data = np.array(['2015-01-01', '2015-01-02'], dtype=[('date', 'S10')])
>>> rnp.array2root(data, 'test.root', treename='data', mode='recreate')
>>> data = rnp.root2array('test.root', treename='data')
>>> data
array([([50, 48, 49, 53, 45, 48, 49, 45, 48, 49],),
       ([50, 48, 49, 53, 45, 48, 49, 45, 48, 50],)], 
      dtype=[('date', 'i1', (10,))])
>>> data.view('S10')
array(['2015-01-01', '2015-01-02'], 
      dtype='|S10')
```

**Comment by MaxNoe** [comment] 2015-06-14 13:25
Why is there no way? The root datatype should provide the information. One could use the same mapping of TYPES_NUMPY2ROOT the other way around

**Comment by ndawe** [comment] 2015-06-14 13:30
In the ROOT file ``np.dtype(('i1', (10,)))`` and ``np.dtype('S10')`` both end up as ``char[10]`` and then from ``char[10]`` alone it is not possible to determine the original view.

**Comment by MaxNoe** [comment] 2015-06-14 13:33
But the Branch description should contain an 'C' for character string array.

**Comment by MaxNoe** [comment] 2015-06-14 13:34
Oh, I see you used the 'B' root datatype, shouldn't be the 'C' datatype be more suited and solve the problem?

**Comment by ndawe** [comment] 2015-06-15 01:24
Yes, you are right. We can use C to distinguish the two purposes. The bytes are the same either way, but C assumes null termination.

**Comment by ndawe** [comment] 2015-06-16 14:05
Got it working. You're welcome to test for yourself:

```
pip install --upgrade --user https://github.com/ndawe/root_numpy/zipball/master
```

```python
>>> import numpy as np
>>> import root_numpy as rnp
>>> data = np.array(['2015-01-01', '2015-01-02'], dtype=[('date', 'S10')])
>>> rnp.array2root(data, 'test.root', treename='data', mode='recreate')
>>> rnp.root2array('test.root', treename='data')
array([('2015-01-01',), ('2015-01-02',)], 
      dtype=[('date', 'S10')])
```

**Comment by MaxNoe** [comment] 2015-06-16 14:23
This seems not to be stable. 

Some times it works but most of the time it freezes. One time I even got a segfault.

**Comment by ndawe** [comment] 2015-06-17 00:59
It's stable for me, but I'm using ROOT 6.03/03. What's your traceback?

**Comment by ndawe** [comment] 2015-06-17 03:43
Actually I can reproduce the issue with a larger array. Working on it.

**Comment by ndawe** [comment] 2015-06-17 05:57
Should be fixed now. Stable on my end anyway. It was not handling the null-termination properly. I'm fairly confident that it's implemented correctly now.

```
pip install --upgrade --user https://github.com/ndawe/root_numpy/zipball/master
```

**Comment by MaxNoe** [comment] 2015-06-17 07:37
Yes, now it works!

Thanks for your effort! Great.

**Comment by ndawe** [comment] 2015-06-17 08:26
Nice. Thanks for testing. This will be included in the next tag. I'll close this issue once I've merged it.

**Comment by ndawe** [comment] 2015-06-19 01:28
Merged with further improvements.

**Closed by ndawe** 2015-06-19 01:28 UTC
